name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: raster-calc
            asset_name: raster-calc-${{ github.ref_name }}-linux-x86_64
          - os: windows-latest
            artifact_name: raster-calc.exe
            asset_name: raster-calc-${{ github.ref_name }}-windows-x86_64
          - os: macos-latest
            artifact_name: raster-calc
            asset_name: raster-calc-${{ github.ref_name }}-macos-x86_64

    steps:
    - uses: actions/checkout@v3
    
    - name: Install GDAL (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev gdal-bin
    
    - name: Install GDAL (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gdal
    
    - name: Install GDAL (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        # Download and install OSGeo4W which includes GDAL
        curl -L -o osgeo4w-setup.exe https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe
        .\osgeo4w-setup.exe --quiet-mode --no-desktop --no-startmenu --no-shortcuts --upgrade-also --site http://download.osgeo.org/osgeo4w/v2 --packages gdal
        echo "GDAL_HOME=C:\OSGeo4W" >> $env:GITHUB_ENV
        echo "C:\OSGeo4W\bin" >> $env:GITHUB_PATH
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Set PKG_CONFIG_PATH (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "PKG_CONFIG_PATH=C:\OSGeo4W\lib\pkgconfig" >> $env:GITHUB_ENV
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Compress artifacts (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/release
        tar czvf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
        
    - name: Compress artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd target/release
        7z a ${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}
    
    - name: Upload artifacts (Unix)
      if: matrix.os != 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/release/${{ matrix.asset_name }}.tar.gz
        asset_name: ${{ matrix.asset_name }}.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/release/${{ matrix.asset_name }}.zip
        asset_name: ${{ matrix.asset_name }}.zip
        asset_content_type: application/zip

  # Separate job for ARM build
  build-arm:
    name: Build Linux ARM64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build ARM64 in Docker
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multiarch --driver docker-container --use
        docker buildx inspect --bootstrap
        
        # Create Dockerfile for ARM build
        cat > Dockerfile << 'EOF'
        FROM arm64v8/rust:slim
        
        RUN apt-get update && apt-get install -y \
            build-essential \
            libgdal-dev \
            gdal-bin \
            pkg-config
        
        WORKDIR /src
        COPY . .
        
        RUN cargo build --release
        
        CMD ["cp", "-r", "/src/target/release/raster-calc", "/output/"]
        EOF
        
        # Create output directory
        mkdir -p output
        
        # Build in Docker
        docker buildx build --platform linux/arm64 -t raster-calc-arm-builder -f Dockerfile .
        
        # Run container to copy binary to host
        docker run --platform linux/arm64 --rm -v $(pwd)/output:/output raster-calc-arm-builder
        
        # Compress the binary
        cd output
        tar czvf raster-calc-$